# Configure a default setup of Home Assistant (frontend, history, api, etc)
default_config:


frontend:
  themes: !include_dir_merge_named themes



panel_iframe: !include panel_iframe.yaml



homeassistant:
  customize: !include customize.yaml



# https://www.home-assistant.io/integrations/recorder
recorder:
  #purge_keep_days: 8
  #db_url: sqlite:////media/home-assistant_v2.db
  exclude:
    entities:
      - sensor.processor_use
      - sensor.memory_use_percent
      - sensor.cpu_temperature
      - sensor.shelly_shem_c7ec27_1_current_consumption
      - sun.sun
      #nuevos
      - media_player.tv_salon
      - media_player.android
      - device_tracker.sagemcom_broadband_sas_77_ba_ec #router



#https://www.home-assistant.io/components/shell_command/
shell_command:
  actualizar_fuelio: !secret actualizar_fuelio



#https://www.home-assistant.io/components/http/
http:
 ssl_certificate: /ssl/fullchain.pem
 ssl_key: /ssl/privkey.pem



sensor: !include sensor.yaml
input_boolean: !include input_boolean.yaml
timer: !include timer.yaml
notify: !include notify.yaml



#TELEGRAM
#https://www.home-assistant.io/components/telegram_bot
telegram_bot:
  - platform: polling
    api_key: !secret telegram_apy_key
    allowed_chat_ids:
      - !secret telegram_idchat1
      - !secret telegram_idchat2



# https://www.home-assistant.io/components/switch.template/
# https://www.home-assistant.io/components/sensor.command_line/
# https://domology.es/scripts-y-comandos-ssh-en-home-assistant/
switch:

  - platform: command_line
    switches:

     kodi:
      command_on: >
        ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "sudo systemctl restart kodi"
      command_off: >
        ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "sudo systemctl stop kodi"
      command_state: >
        ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "sudo systemctl is-active kodi"
      value_template: '{{ value == "active" }}'

     filebrowser:
      command_on: >
        ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "sudo filebrowser -a 192.168.0.2 -p 8888 -r /"
      command_off: >
        ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "sudo pkill filebrowser"
      command_state: >
        nc -z 192.168.0.2 8888; echo $?
      value_template: '{{ value == "0" }}'

     webmin:
      command_on: >
        ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "sudo systemctl restart webmin"
      command_off: >
        ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "sudo systemctl stop webmin"
      command_state: >
        ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "sudo systemctl is-active webmin"
      value_template: '{{ value == "active" }}'

     wireguard:
      command_on: >
        ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "sudo docker start addon_a0d7b954_wireguard"
      command_off: >
        ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "sudo docker stop addon_a0d7b954_wireguard"
      command_state: >
        ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "sudo docker ps | grep addon_a0d7b954_wireguard | wc -l"
      value_template: '{{ value == "1" }}'       

     disco_externo:
      command_on: >
        ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "sudo echo '2-2' | sudo tee /sys/bus/usb/drivers/usb/bind; sudo sleep 5; sudo mount /media/DISCO_USB_EXT"
      command_off: >
        ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "sudo umount /media/DISCO_USB_EXT; sudo sleep 5; sudo echo '2-2' | sudo tee /sys/bus/usb/drivers/usb/unbind"
      command_state: >
        ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "sudo cat /etc/mtab | grep DISCO_USB_EXT | wc -l"
      value_template: '{{ value == "1" }}'       

     reiniciar_pi:
        command_on: >
         ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "sudo reboot"
         
     apagar_pi:
        command_on: >
         ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "sudo poweroff"

  #TERMOSTATO este switch es necesario para que funcione fluoreon
  - platform: floureon
    name: Termostato_Casa
    mac: !secret mac_termostato
    host: 192.168.0.102
    turn_off_mode: turn_off
    turn_on_mode: 22.0 #tiene que ser con decimal o falla



#TERMOSTATO
#https://community.home-assistant.io/t/floureon-beok-and-other-broadlink-based-thermostat-component/153775/56
climate:
  platform: floureon
  name: Termostato_Casa
  mac: !secret mac_termostato
  host: 192.168.0.102
  use_external_temp: false



#https://www.home-assistant.io/integrations/yeelight
discovery:
  ignore:
    - yeelight
yeelight:
  devices:
    192.168.0.101:
      name: Luz Salón



#https://www.home-assistant.io/integrations/xiaomi_aqara/
xiaomi_aqara:
  discovery_retry: 2
  gateways:
    - key: !secret xiaomi_aqara_key



#https://github.com/StyraHem/ShellyForHASS
shelly:
  discover_by_ip:
    - '192.168.0.104'
    - '192.168.0.105'
    - '192.168.0.106'
    - '192.168.0.107'
    - '192.168.0.108'



#https://www.home-assistant.io/integrations/utility_meter/
#https://www.youtube.com/watch?v=SdG7jUyk8BA
utility_meter:
  daily_energy_rest:
    source: sensor.shelly_em_energia_total_rest
    cycle: daily
  monthly_energy_rest:
    source: sensor.shelly_em_energia_total_rest
    cycle: monthly



#https://www.home-assistant.io/components/tts.google/
tts:
  - platform: google_translate
    language: 'es'



#https://www.home-assistant.io/components/google_assistant/
google_assistant:
  project_id: gassistantha
  service_account: !include SERVICE_ACCOUNT.JSON
  report_state: true
  expose_by_default: true
  entity_config:
    switch.termostato_casa:
        expose: false
    sensor.humedad_dormitorio:
        expose: false
    sensor.temperatura_dormitorio:
        expose: false
    switch.shelly_shem_c7ec27:
        expose: false
    binary_sensor.puerta_casa:
        expose: false
    light.luz_salon:
        expose: false
    switch.apagar_pi:
        expose: false
    switch.reiniciar_pi:
        expose: false
    group.persianas_salon:
        expose: false
    sensor.humedad_salon:
        expose: false
    sensor.temperatura_salon:
        expose: false
    media_player.kodi:
        expose: false
    cover.shelly_shsw_25_40f520001121:
        expose: false
    cover.shelly_shsw_25_40f52000bceb:
        expose: false
    cover.shelly_shsw_25_40f520005f30:
        expose: false
    cover.shelly_shsw_25_3c6105e43a4a:
        expose: false
    cover.shelly_shsw_25_3c6105e33608:
        expose: false
    binary_sensor.puerta_trastero:
        expose: false
    media_player.tv:
        expose: false
    switch.encender_television:
        name: television
    switch.wireguard:
        name: VPN
    automation.tv_off_y_usb_on_usb_off:
        expose: false



group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml



#https://www.youtube.com/watch?v=rKIHoqxxMek&list=PLst9mKBGfYJdcLU0MG3BEl7b00KC9f13a&index=3&t=511s
# influxdb:
#   host: a0d7b954-influxdb
#   port: 8086
#   database: homeassistant
#   username:  !secret influx
#   password: !secret influx
#   max_retries: 3
#   default_measurement: state



#DOODS https://www.youtube.com/watch?v=27D5ue5jcBo&list=PLDp1j6OBvIqbrCfu8_RbvMCLJM8E5G7x2&index=2
# image_processing:
#   - platform: doods
#     scan_interval: 30
#     url: "http://172.30.33.4:18080"
#     timeout: 60
#     detector: default
#     source:
#       - entity_id: camera.camara_salon
#     file_out:
#       - "/media/{{ camera_entity.split('.')[1] }}_latest.jpg"
#       - "/media/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
#     confidence: 65
#     labels:
#       - name: person
#         confidence: 60
#       - name: cell phone
#         confidence: 65



#https://www.home-assistant.io/components/ifttt/
# ifttt:
#   key: !secret ifttt_key


#https://www.home-assistant.io/integrations/calendar.google#prerequisites
#ojo revoke el acceso de google calendar
# google:
#   client_id: !secret google_client_id
#   client_secret: !secret google_client_secret