# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:



frontend:
  themes: !include_dir_merge_named themes



panel_iframe: !include panel_iframe.yaml



homeassistant:
  customize: !include customize.yaml



#https://www.home-assistant.io/components/shell_command/
shell_command:
  actualizar_fuelio: !secret actualizar_fuelio
  actualizar_pihole: >
    ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "sudo docker exec pihole pihole -g"



#https://www.home-assistant.io/components/http/
http:
# base_url: !secret base_url
 ssl_certificate: /ssl/fullchain.pem
 ssl_key: /ssl/privkey.pem



sensor: !include sensor.yaml



notify: !include notify.yaml



#https://www.home-assistant.io/integrations/webostv
webostv:
  host: 192.168.0.99
  name: tv_salon



#https://www.home-assistant.io/integrations/kodi
media_player:
  - platform: kodi
    host: 192.168.0.2
    username: !secret kodi_username
    password: !secret kodi_password



#TELEGRAM
#https://www.home-assistant.io/components/telegram_bot
telegram_bot:
  - platform: polling
    api_key: !secret telegram_apy_key
    allowed_chat_ids:
      - !secret telegram_idchat1
      - !secret telegram_idchat2



#https://www.home-assistant.io/components/switch.template/
# https://www.home-assistant.io/components/sensor.command_line/
# https://domology.es/scripts-y-comandos-ssh-en-home-assistant/
switch:
  - platform: command_line
    switches:

     kodi:
      command_on: >
        ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "sudo systemctl restart kodi"
      command_off: >
        ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "sudo systemctl stop kodi"
      command_state: >
        ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "systemctl status kodi --full | grep -oc 'Active: active (running)'"
      value_template: '{{ value == "1" }}'

     webmin:
      command_on: >
        ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "sudo systemctl restart webmin"
      command_off: >
        ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "sudo systemctl stop webmin"
      command_state: >
        ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "systemctl status webmin --full | grep -oc 'Active: active (running)'"
      value_template: '{{ value == "1" }}'

     pihole:
      command_on: >
        ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "sudo docker start pihole"
      command_off: >
        ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "sudo docker stop pihole"
      command_state: >
        ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "docker ps | grep pihole | wc -l"
      value_template: '{{ value == "1" }}'

     wireguard:
      command_on: >
        ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "docker start addon_a0d7b954_wireguard"
      command_off: >
        ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "docker stop addon_a0d7b954_wireguard"
      command_state: >
        ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "docker ps | grep addon_a0d7b954_wireguard | wc -l"
      value_template: '{{ value == "1" }}'       

     disco_externo:
      command_on: >
        ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "sudo echo '1-1.3' | sudo tee /sys/bus/usb/drivers/usb/bind; sudo sleep 5; sudo mount /media/DISCO_USB_EXT"
      command_off: >
        ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "sudo umount /media/DISCO_USB_EXT; sudo sleep 5; sudo echo '1-1.3' | sudo tee /sys/bus/usb/drivers/usb/unbind"
      command_state: >
        ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "sudo cat /etc/mtab | grep DISCO_USB_EXT | wc -l"
      value_template: '{{ value == "1" }}'       

     reiniciar_pi:
        command_on: >
         ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "sudo reboot"
         
     apagar_pi:
        command_on: >
         ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "sudo poweroff"

     encender_television:
        command_on: >
         ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "sudo echo 'on 0' | cec-client -s"

     apagar_television:
        command_on: >
         ssh -i id_rsa -o StrictHostKeyChecking=no pi@192.168.0.2 "sudo echo 'standby 0' | cec-client -s"


  #TERMOSTATO este switch es necesario para que funcione fluoreon
  - platform: floureon
    name: Termostato_Casa
    mac: !secret mac_termostato
    host: 192.168.0.102
    turn_off_mode: turn_off
    turn_on_mode: 22.0 #tiene que ser con decimal o falla



#TERMOSTATO
#https://community.home-assistant.io/t/floureon-beok-and-other-broadlink-based-thermostat-component/153775/56
climate:
  platform: floureon
  name: Termostato_Casa
  mac: !secret mac_termostato
  host: 192.168.0.102
  use_external_temp: false



#https://www.home-assistant.io/components/ifttt/
# ifttt:
#   key: !secret ifttt_key



#https://www.home-assistant.io/integrations/yeelight
discovery:
  ignore:
    - yeelight
yeelight:
  devices:
    192.168.0.101:
      name: Luz Salón



#https://www.home-assistant.io/integrations/xiaomi_aqara/
xiaomi_aqara:
  discovery_retry: 3
  gateways:
    - key: !secret xiaomi_aqara_key



#https://www.youtube.com/watch?v=rKIHoqxxMek&list=PLst9mKBGfYJdcLU0MG3BEl7b00KC9f13a&index=3&t=511s
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username:  !secret influx
  password: !secret influx
  max_retries: 3
  default_measurement: state



#https://github.com/StyraHem/ShellyForHASS
shelly:
  discover_by_ip:
    - '192.168.0.104'
    - '192.168.0.105'
    - '192.168.0.106'
    - '192.168.0.107'
    - '192.168.0.108'



#https://www.home-assistant.io/integrations/utility_meter/
#https://www.youtube.com/watch?v=SdG7jUyk8BA
utility_meter:
  daily_energy:
    source: sensor.shelly_shem_c7ec27_1_total_consumption
    cycle: daily
  monthly_energy:
    source: sensor.shelly_shem_c7ec27_1_total_consumption
    cycle: monthly



#https://www.home-assistant.io/integrations/nmap_tracker
device_tracker:
  - platform: nmap_tracker
    hosts:
      - 192.168.0.3 #sobremesa
      - 192.168.0.4 #portatil
    home_interval: 60 #escanea cada minuto la red



#https://www.home-assistant.io/components/tts.google/
tts:
  - platform: google_translate
    language: 'es'



#https://www.home-assistant.io/integrations/calendar.google#prerequisites
# google:
#   client_id: !secret google_client_id
#   client_secret: !secret google_client_secret



#https://www.home-assistant.io/components/google_assistant/
google_assistant:
  project_id: gassistantha
  service_account: !include SERVICE_ACCOUNT.JSON
  report_state: true
  entity_config:
    switch.termostato_casa:
        expose: false
    sensor.humedad_dormitorio:
        expose: false
    sensor.temperatura_dormitorio:
        expose: false
    switch.shelly_shem_c7ec27:
        expose: false
    binary_sensor.puerta_casa:
        expose: false
    light.luz_salon:
        expose: false
    switch.apagar_pi:
        expose: false
    switch.reiniciar_pi:
        expose: false
    group.persianas_salon:
        expose: false
    sensor.humedad_salon:
        expose: false
    sensor.temperatura_salon:
        expose: false
    media_player.kodi:
        expose: false
    cover.shelly_shsw_25_40f520001121:
        expose: false
    cover.shelly_shsw_25_40f52000bceb:
        expose: false
    cover.shelly_shsw_25_40f520005f30:
        expose: false
    binary_sensor.puerta_trastero:
        expose: false
    media_player.tv:
        expose: false        

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml